#!/usr/bin/env bash
# demo-kit-export.sh — Package a clean, client-ready demo bundle.
#
# Exports the h7-demo-kit into a self-contained directory (no run/ state, no
# development cruft, no .git) that can be handed directly to a client or used
# for a standardized live demo.
#
# Usage:
#   bash scripts/demo-kit-export.sh [OUTPUT_DIR]
#
# Default output: ../h7-demo-kit-export-YYYY-MM-DD/
#
# The export includes:
#   Makefile, fixtures/, scripts/, docs/, SKILL.md, SECURITY.md, README.md
#   A pre-seeded run/baseline.json (offline-fallback, no BTF required)
#   The DORA/NIS2 checklist and EU AI Act traceability doc
#   A generated empty CRL skeleton (gen-crl.py --help embedded)
#
# The export does NOT include:
#   run/bin/, run/keys/, run/logs/, run/alerts/ (client generates their own)
#   .git/, .gitignore

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KIT_ROOT="$(dirname "$SCRIPT_DIR")"
DATE="$(date +%Y-%m-%d)"
OUTPUT_DIR="${1:-"$(dirname "$KIT_ROOT")/h7-demo-kit-export-${DATE}"}"

echo "[demo-kit-export] Building export → ${OUTPUT_DIR}"

# --- Exclude list ---
EXCLUDES=(
    ".git"
    ".gitignore"
    "run/"
    "__pycache__"
    "*.pyc"
    "*.pyo"
    ".DS_Store"
    "docs/demo/*.cast"
)

# Build rsync exclude args
RSYNC_EXCLUDES=()
for e in "${EXCLUDES[@]}"; do
    RSYNC_EXCLUDES+=("--exclude=${e}")
done

mkdir -p "${OUTPUT_DIR}"

rsync -a --delete \
    "${RSYNC_EXCLUDES[@]}" \
    "${KIT_ROOT}/" \
    "${OUTPUT_DIR}/"

# --- Pre-seed offline baseline ---
echo "[demo-kit-export] Seeding offline baseline..."
mkdir -p "${OUTPUT_DIR}/run/logs" "${OUTPUT_DIR}/run/alerts" "${OUTPUT_DIR}/run/reports"
python3 "${SCRIPT_DIR}/seed-offline-baseline.py" \
    --fixture "${KIT_ROOT}/fixtures/baseline.example.json" \
    --output  "${OUTPUT_DIR}/run/baseline.json" 2>/dev/null || true

# --- README addendum for export ---
cat >> "${OUTPUT_DIR}/README.md" << 'ADDENDUM'

---

## Export bundle (client pre-configured)

This bundle was exported with a pre-seeded offline baseline (`run/baseline.json`)
so that `make up` works immediately without requiring BTF or `sudo calibrate`.

Quick start (no BTF required):
```bash
make setup        # fetch binaries + generate keys
make up           # sensor + sinkhole (uses pre-seeded baseline)
make attack-vercel
make verify-alert
make gen-audit-package
```

For a live demo walkthrough: `docs/gtm/DEMO-GUIDE.md`
For compliance documentation: `docs/DORA-NIS2-CHECKLIST.md`
For EU AI Act traceability: `docs/EU-AI-ACT-TRACEABILITY.md`
ADDENDUM

# --- Manifest ---
MANIFEST="${OUTPUT_DIR}/EXPORT-MANIFEST.txt"
{
    echo "h7-demo-kit export — ${DATE}"
    echo "Generated by: demo-kit-export.sh"
    echo "Source: ${KIT_ROOT}"
    echo ""
    echo "Files included:"
    find "${OUTPUT_DIR}" -type f | sort | sed "s|${OUTPUT_DIR}/||"
} > "${MANIFEST}"

FILE_COUNT=$(find "${OUTPUT_DIR}" -type f | wc -l)
echo "[demo-kit-export] Done → ${OUTPUT_DIR}"
echo "  files : ${FILE_COUNT}"
echo "  size  : $(du -sh "${OUTPUT_DIR}" | cut -f1)"
echo ""
echo "  Next steps:"
echo "  1. cd ${OUTPUT_DIR}"
echo "  2. make setup"
echo "  3. make up && make attack-vercel && make verify-alert"
echo "  4. make gen-audit-package"
